version: '3.6'
services:
  web:
    # Calculate your upgrade path here: https://gitlab-com.gitlab.io/support/toolbox/upgrade-path/
    #image: 'gitlab/gitlab-ee:latest'
    #image: 'gitlab/gitlab-ee:15.4.6-ee.0'
    #image: 'gitlab/gitlab-ee:15.11.13-ee.0'
    #image: 'gitlab/gitlab-ee:16.3.3-ee.0'
    #image: 'gitlab/gitlab-ee:16.3.6-ee.0'
    image: 'gitlab/gitlab-ee:16.5.1-ee.0'
    restart: always
    hostname: 'gitlab.hugo-klepsch.tech'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.hugo-klepsch.tech'
    ports:
      - '8929:80'
      - '2224:22'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
