version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.hugo-klepsch.tech'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.hugo-klepsch.tech'
    ports:
      - '8929:80'
      - '2224:22'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
